# Site settings
title: Wuzaa
description: Lost Wuzaa, die neue art Skyblock zu spielen.
keywords: Minecraft, Lost, Wuzaa, Skyblock
author: Hexagon457 
baseurl: "/Wuzaa" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
logo: "/img/logo.png"
menu:
  - title: Home
    url: /Wuzaa
  - title: Anleitungen
    url: /Wuzaa/help
  - title: Archiv
    url: /Wuzaa/archive
  - title: Regeln
    url: /Wuzaa/2019/04/22/Regeln
  - title: NPC Map
    url:  http://map.wuzaa.nanoxido.de/
  - tilte: Questübersicht
    url: https://google.de
  - title: FAQ
    url: https://google.de
  - title: Team
    url: https://google.de
