# Site settings
title: Modern Blog
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Wferr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
logo: "/img/logo.png"
menu:
  - title: Home
    url: /Wuzaa
  - title: Anleitungen
    url: /Wuzaa/help
  - title: Test
    url: https://google.de
