# Site settings
title: Wuzaa
description: Lost Wuzaa, die neue art Skyblock zu spielen.
keywords: Minecraft, Lost, Wuzaa
author: Hexagon457 
baseurl: "/Wuzaa" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
logo: "/img/logo.png"
footerLinks:
  - title: Test
    url: https://google.de
  - title: Test 2
    url: https://google.de
menu:
  - title: Home
    url: /Wuzaa
  - title: Anleitungen
    url: /Wuzaa/help
  - title: Archiv
    url: /Wuzaa/archive
  - title: Test
    url: https://google.de
